name: "lego"

trainer:
  output_path: "output/nerf"
  max_steps: 30000
  val_interval: 5000
  lambda_dssim: 0.2

  densify_start_iter: 500
  densify_stop_iter: 15000
  prune_interval: 100
  duplicate_interval: 100
  opacity_reset_interval: 3000
  
  gaussian_points:
    gaussian_type: "GaussianSplatting"
    max_sh_degree: 3
    percent_dense: 0.01
    densify_grad_threshold: 0.0002
    min_opacity: 0.005
    points_cloud:
      trainable: true
      initializer:
        init_type: 'random'
        num_points: 100000
        radius: 1.3
        feat_dim: 3
  optimizer:
    name: Adam
    args:
      eps: 1e-15
    params:
      points_cloud.position:
        lr: 0.00016
      points_cloud.features:
        lr: 0.0025
      points_cloud.features_rest:
        lr: 0.000125 # features/20
      points_cloud.scaling:
        lr: 0.005
      points_cloud.rotation:
        lr: 0.001
      points_cloud.opacity:
        lr: 0.05
  scheduler:
    name: "get_expon_lr_func"
    max_steps: ${trainer.max_steps}
    params:
      points_cloud.position:
        init:  0.00016
        final: 0.0000016
      # points_cloud.rotation:
      #   init:  0.001
      #   final: 0.0001

  dataset:
    data_path: "/home/clz/data/nerf_synthetic/lego"
    data_type: "NerfReFormat"
    cached_image: True
    shuffle: True
    batch_size: 1
    num_workers: 0
    white_bg: True

  renderer:
    name: "splatting"